CREATE TABLE UUSER (USERNAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255), PASSWORD VARCHAR(255), PRIMARY KEY (USERNAME));
CREATE TABLE GROUPS (USERNAME VARCHAR(255) NOT NULL, GROUPS VARCHAR(255) NOT NULL, PRIMARY KEY (USERNAME, GROUPS));
CREATE TABLE CHUNK (HASH char(64), CREATED DATETIME NOT NULL, LASTACCESSED DATETIME NOT NULL, PRIMARY KEY (HASH));

-- INSERT STATEMENTS FOR DEVELOPMENT
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("admin", "admin@mibox", "admin");
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("user",  "user@mibox",  "user" );
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("user2",  "user2@mibox",  "user" );
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("user3",  "user3@mibox",  "user" );
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("admin", "admin");
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("user",  "user" );
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("user2",  "user" );
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("user3",  "user" );