CREATE TABLE USER (USERNAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255), PASSWORD VARCHAR(255), PRIMARY KEY (USERNAME));
CREATE TABLE CHUNKHDDMAPPING (ID char(64), VALUE char(36), PRIMARY KEY (ID));
CREATE INDEX INDEX_CHUNKHDDMAPPING_VALUE ON CHUNKHDDMAPPING (VALUE);
CREATE TABLE GROUPS (USERNAME VARCHAR(255) NOT NULL, GROUPS VARCHAR(255) NOT NULL, PRIMARY KEY (USERNAME, GROUPS));
