CREATE TABLE UUSER (USERNAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL, PRIMARY KEY (USERNAME));
CREATE TABLE GROUPS (USERNAME VARCHAR(255) NOT NULL, GROUPS VARCHAR(255) NOT NULL, PRIMARY KEY (USERNAME, GROUPS));
CREATE TABLE CHUNK (HASH char(64), CREATED DATETIME NOT NULL, LASTACCESSED DATETIME NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE UUSER_CHUNK (UUSER_USERNAME VARCHAR(255) NOT NULL, CHUNK_HASH char(64), PRIMARY KEY (UUSER_USERNAME, CHUNK_HASH));
ALTER TABLE UUSER_CHUNK ADD CONSTRAINT FK_UUSER_CHUNK_CHUNK_HASH FOREIGN KEY (CHUNK_HASH) REFERENCES CHUNK (HASH);
ALTER TABLE UUSER_CHUNK ADD CONSTRAINT FK_UUSER_CHUNK_UUSER_USERNAME FOREIGN KEY (UUSER_USERNAME) REFERENCES UUSER (USERNAME);
