CREATE TABLE UUSER (USERNAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL, PRIMARY KEY (USERNAME));
CREATE TABLE GROUPS (USERNAME VARCHAR(255) NOT NULL, GROUPS VARCHAR(255) NOT NULL, PRIMARY KEY (USERNAME, GROUPS));
CREATE TABLE CHUNK (HASH char(64), CREATED DATETIME NOT NULL, LASTACCESSED DATETIME NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE UUSER_CHUNK (UUSER_USERNAME VARCHAR(255) NOT NULL, CHUNK_HASH char(64), PRIMARY KEY (UUSER_USERNAME, CHUNK_HASH));
ALTER TABLE UUSER_CHUNK ADD CONSTRAINT FK_UUSER_CHUNK_CHUNK_HASH FOREIGN KEY (CHUNK_HASH) REFERENCES CHUNK (HASH);
ALTER TABLE UUSER_CHUNK ADD CONSTRAINT FK_UUSER_CHUNK_UUSER_USERNAME FOREIGN KEY (UUSER_USERNAME) REFERENCES UUSER (USERNAME);


-- INSERT STATEMENTS FOR DEVELOPMENT
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("admin", "admin@mibox", "admin");
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("user",  "user@mibox",  "user" );
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("user2",  "user2@mibox",  "user" );
INSERT INTO UUSER (USERNAME, EMAIL, PASSWORD) VALUES ("user3",  "user3@mibox",  "user" );
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("admin", "admin");
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("user",  "user" );
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("user2",  "user" );
INSERT INTO GROUPS (USERNAME, GROUPS) VALUES ("user3",  "user" );