CREATE TABLE UUSER (USERNAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255), PASSWORD VARCHAR(255), PRIMARY KEY (USERNAME));
CREATE TABLE GROUPS (USERNAME VARCHAR(255) NOT NULL, GROUPS VARCHAR(255) NOT NULL, PRIMARY KEY (USERNAME, GROUPS));
CREATE TABLE CHUNK (HASH char(64), CREATED DATETIME NOT NULL, LASTACCESSED DATETIME NOT NULL, PRIMARY KEY (HASH));
